### PR TITLE
change logic for nuke animation feature

### LINKED ISSUE #318: [Client] - Fix nuke animation feature in front-end
The Nuke Land animation doesn't work properly; it's buggy and confuses the game.

Make the logic much easier to read and manage in the front end.

### PR DESCRIPTION
**Pull request by Gianfranco99**
this pr resolves #318

### CODE REVIEW

File: client/src/lib/stores/nuke.svelte.ts
Comment (0xMugen) [inline client/src/lib/stores/nuke.svelte.ts:1]: Move the nukeStore to the new locationsToNuke class. Maybe worth turning it into a big function for the ... feat

File: client/src/lib/utils/taxes.ts [hunk 1]
```diff
@@ -15,18 +15,28 @@ export type TaxData = {
...
   // aggregate the two arrays with total tax per token
   const tokenTaxMap: Record<string, CurrencyAmount> = {};
 
   for (const tax of (await land.getNextClaim()) ?? []) {
+    if (tax.canBeNuked) {
+      locationsToNuke.push({ location: tax.landLocation, nukable: true });
+    } else {
+      locationsToNuke.push({ location: tax.landLocation, nukable: false });
+    }
+
```
Comment (knownasred) [inline client/src/lib/utils/taxes.ts:39]:
```suggestion
      locationsToNuke.push({ location: tax.landLocation, nukable: tax.canBeNuked });

```

File: client/src/lib/stores/nuke.svelte.ts [hunk 2]
```diff
@@ -1,79 +1,28 @@
...
+export function clearPending(location: string) {
+  const newPending = { ...nukeStore.pending };
+  delete newPending[location];
+  nukeStore.pending = newPending;
 }
 
-//TODO make this work
-export const getNukeData = async () => {
-  const { client: sdk } = useDojo();
+export function setNuking(location: string) {
```
Comment (knownasred) [inline client/src/lib/stores/nuke.svelte.ts:19]: `markAsNuking` might be more appropriate, as you are not calling a dumb setter, and to match with the `clear*` functions

File: client/src/lib/components/land/land-tax-claimer.svelte [hunk 3]
```diff
@@ -74,6 +75,14 @@
     const result = await getAggregatedTaxes(land);
 
     aggregatedTaxes = result.taxes;
+
+    const nukables = result.nukables;
+
+    nukables.forEach((land) => {
+      if (land.nukable) {
+        setPending(land.location);
+      }
```
Comment (knownasred) [inline client/src/lib/components/land/land-tax-claimer.svelte:84]: No removing from the pending if it is no longer nukable?

File: client/src/lib/components/map/map.svelte [hunk 4]
```diff
@@ -44,6 +45,10 @@
             land: land,
             claimable: true,
           };
+          let isNuking = $derived(nukeStore.nuking[land.location] === true);
```
Comment (knownasred) [inline client/src/lib/components/map/map.svelte:48]: No need to use a $derived in an effect, especially if it's only used in an IF afterwards.

**Review by knownasred — CHANGES_REQUESTED** [review]

**Review by knownasred — APPROVED** [review]
:shipit:

**Comment by knownasred** [comment]
### Merge activity

* **Apr 18, 6:14 AM EDT**: The merge label 'Merge queue' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=RuneLabsxyz&repo=PonziLand) once it meets the requirements.
